
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql
before_install:
  - npm install sequelize-cli -g
env:
  global:
  - NODE_ENV=test
  - DATABASE_TEST=postgres://postgres:@127.0.0.1:5432/books_test

before_script:
  - psql -c 'drop database if exists books_test;' -U postgres
  - psql -c 'create database books_test;' -U postgres
  - npm run build
  - npm install -g sequelize-cli
  - npm run migrate
script:
  - npm run test
after_success:
  - npm run coverage
